name: Eslint

on:
  push:
    branches: [master]
  pull_request:
    branches: "*"

permissions:
  contents: read

jobs:
  general:
    runs-on: ubuntu-latest
    steps:
      # Clone repository
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      # Install dependencies
      - name: "Install Dependencies"
        run: npm ci

      - name: "Run Eslint"
        run: npm run lint:ci
