name: Jest

on:
  push:
    branches: [master]
  pull_request:
    branches: "*"

permissions:
  contents: read

jobs:
  general:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Install Dependencies"
        run: npm ci

      - name: "Run Jest"
        run: npm run test:ci
